name: Gray
title: GrayInFilm
description: Gray In Film is a personal website maintained and managed by Grace Icay.
tags:
  - grace+icay
  - QA+blog
  - techblog
  - grayinfilm
  - gray+in+film
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Links
    url: /links
  - title: Recs
    url: /recs
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: mggicay@yahoo.co.jp
# See: https://disqus.com/
#disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
#formspree_form_id: formspree_form_id